#!/bin/sh

export ABCD_USER="$1"
cmd=${SSH_ORIGINAL_COMMAND%% *}

if [ "$cmd" = "git-upload-pack" -o "$cmd" = "git-receive-pack" ]; then
	if grep -Fxq $ABCD_USER $HOME/admins ; then
		exec sh -c "$SSH_ORIGINAL_COMMAND"
	fi

	echo Permission denied
	exit 1
fi

exec abcd-server
